name: charity_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.5
  firebase_auth: ^4.17.0
  firebase_core: ^2.27.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - images/children.jpg
    - images/google.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/static/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-VariableFont.ttf
  uses-material-design: true
